# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit_margins_cpp <- function(data, nlevels, mult, xmin, xmax, bw, deg, weights, num_threads) {
    .Call(`_cvinereg_fit_margins_cpp`, data, nlevels, mult, xmin, xmax, bw, deg, weights, num_threads)
}

select_cvine_cpp <- function(data, family_set, par_method, nonpar_method, mult, selcrit, weights, psi0, preselect_families, cores, var_types) {
    .Call(`_cvinereg_select_cvine_cpp`, data, family_set, par_method, nonpar_method, mult, selcrit, weights, psi0, preselect_families, cores, var_types)
}

cond_cvine_quantile_cpp <- function(alpha, u, vinecop_r, num_threads) {
    .Call(`_cvinereg_cond_cvine_quantile_cpp`, alpha, u, vinecop_r, num_threads)
}

cond_cvine_dist_cpp <- function(u, vinecop_r, num_threads) {
    .Call(`_cvinereg_cond_cvine_dist_cpp`, u, vinecop_r, num_threads)
}

cond_cvine_dens_cpp <- function(u, vinecop_r, num_threads) {
    .Call(`_cvinereg_cond_cvine_dens_cpp`, u, vinecop_r, num_threads)
}

cond_cvine_loglik_cpp <- function(u, vinecop_r, num_threads) {
    .Call(`_cvinereg_cond_cvine_loglik_cpp`, u, vinecop_r, num_threads)
}

